@startuml Foobr-System
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include DEVICONS/python.puml
!include DEVICONS/database.puml
!include DEVICONS/javascript.puml

left to right direction

Person(user, "User", "Boiling point visitor")
Person(admin, "Administrator", "Boiling point admin")

System_Boundary(bpb, "Boiling Point Bot") {
    Container(bot, "Boiling Point Bot", "Python/Aiogram", "Perform main buisness logic", $sprite="python")
    ContainerDb(db, "Database", "Supabase", "Contain info about users, events, they relations, etc.", $sprite="database")
    Container(scanner, "QR Scanner", "Vue/grammyjs","QR Code Scanner Telegram Web Application", $sprite="javascript")
    Container(form_reader, "Forms", "Quasar", "Form walkthrough Telegram Web Application", $sprite="javascript")
    Container(form_writer, "Forms Creator", "Quasar", "Form creation Telegram Web Application", $sprite="javascript")
    Container(event_sync, "Event Syncronizer", "Typescipt", "Cron, used for synchronization of the leader id events with database", $sprite="javascript")
}

System_Ext(leaderid, "Leader ID", "Provide info about events, users, etc.")
System_Ext(telegram, "Telegram", "Telegram Domain")
System_Ext(sheets, "Google Sheets", "Google Sheets Api")

Rel(user, telegram, "Using to participate in events, saw profile, users top and work with promos", "Telegram/Web App")
Rel(user, scanner, "Using to scan promo QR Codes", "HTTPS")
Rel(user, form_reader, "Using to complete event forms", "HTTPS")

Rel(telegram, bot, "Using to pass requests to bot", "HTTPS/Webhook")

Rel(admin, telegram, "Using to CRUD users, events, etc.", "Telegram/Web App")
Rel(admin, form_writer, "Using to create forms", "HTTPS")
Rel(admin, db, "Using to add some files, CRUD info", "HTTPS/Supabase UI")

Rel(bot, sheets, "Using to update raiting sheet")

Rel(form_reader, telegram, "Using, to push user answers to bot", "HTTPS")
Rel(form_writer, telegram, "Using to push created form to bot", "HTTPS")
Rel(scanner, telegram, "Using to push promo to bot", "HTTPS")

Rel(bot, db, "Using to CRUD info about users, events, etc. Work with files (i. e. images)", "HTTPS/supabase-py")


Rel(event_sync, db, "Using to write events from Leader ID to database", "HTTPS/supabase-js")
Rel(event_sync, leaderid, "Using to synchronize info about events", "sync,HTTPS/Rest")

@enduml
